{{- if .Values.backend.enabled }}
  {{- if .Values.backend.services.config.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $key, $value := .Values.backend.services.config.service.annotations }}
    {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value }}
      {{- end }}
  {{- end }}
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    helm.stargate.spaceone.dev/service: config
  name: config
  namespace: {{ .Release.Namespace }}
spec:
    {{- with .Values.backend.services.config }}
  ports:
    - port: 50051
      protocol: TCP
      {{- if and (or (eq .service.type "NodePort") (eq .service.type "LoadBalancer")) .service.nodePort }}
      nodePort: {{ .service.nodePort }}
      {{- end}}
  selector:
    helm.stargate.spaceone.dev/service: config
  sessionAffinity: None
  type: {{ .service.type }}
    {{- end }}
  {{- end }}
{{- end }}